### ISSUE TITLE
Invalid data format: Invalid passphrase

### ISSUE THREAD

**Issue by gbpusd1212** [webchain-network/old-wallet#231]
``` 
JsonRpcError: Invalid data format: Invalid passphrase
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
    at new JsonRpcError (file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
    at file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
 ```

**Comment by danielwebimp** [comment]
@gbpusd1212 Hi, make sure your password is correct. That error occurs when the password is not OK.
I encourage you to use instead our new Desktop wallet that you can download from here : https://github.com/mintme-com/wallet/releases , Take a backup of your wallet, then import it in the new software installed (Desktop wallet).

> ```
> JsonRpcError: Invalid data format: Invalid passphrase
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
>     at new JsonRpcError (file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
>     at file:///C:/Users/abdul%20salam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
> ```
