### ISSUE TITLE
Invalid address length, expected 40 got 34 bytes

### ISSUE THREAD

**Issue by rizvangs** [webchain-network/old-wallet#232]
``` 
JsonRpcError: Invalid address length, expected 40 got 34 bytes
    at JsonRpcError.ExtendableBuiltin (file:///C:/Program%20Files/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
    at new JsonRpcError (file:///C:/Program%20Files/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
    at file:///C:/Program%20Files/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
 ```

**Comment by rizvangs** [comment]
email me 
rizvangs@gmail.com
