### ISSUE TITLE
Invalid address length, expected 40 got 13 bytes

### ISSUE THREAD

**Issue by MpaapM** [webchain-network/old-wallet#235]
``` 
JsonRpcError: Invalid address length, expected 40 got 13 bytes
    at JsonRpcError.ExtendableBuiltin (file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
    at new JsonRpcError (file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
    at file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
 ```

**Comment by danielwebimp** [comment]
@MpaapM  Hi, make sure your destination address is correct. That error occurs when the destination  address is not OK.
I encourage you to use instead our new Desktop wallet that you can download from here : https://github.com/mintme-com/wallet/releases , Take a backup of your wallet, then import it in the new software installed (Desktop wallet).

> ```
> JsonRpcError: Invalid address length, expected 40 got 13 bytes
>     at JsonRpcError.ExtendableBuiltin (file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25716:30)
>     at new JsonRpcError (file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25745:116)
>     at file:///C:/Users/shabnam/AppData/Local/Programs/MintMeCoinWallet/resources/app.asar/app/index.js:25782:19
> ```
